[package]
name = "gen-dcron"
version = "0.1.0"
authors = ["yangzhenzhen01 <yangzhenzhen01@ke.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
